services:
  - type: web
    name: document-intelligence-api
    runtime: docker
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: VECTOR_STORE
        value: chroma
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: ENVIRONMENT
        value: production
      - key: GROQ_API_KEY
        sync: false
